# Generated by Django 4.2.8 on 2023-12-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCompanyBoqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_original', models.CharField(max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('labor_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_unit_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('code_3_letter', models.CharField(max_length=3)),
                ('numeric_code', models.IntegerField()),
                ('calling_code', models.IntegerField()),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('name_original', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('short_name_tm', models.CharField(max_length=20)),
                ('short_name_ru', models.CharField(max_length=20)),
                ('short_name_en', models.CharField(max_length=20)),
                ('short_name_original', models.CharField(max_length=20)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('name_original', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('code_tm', models.CharField(max_length=10, null=True)),
                ('code_ru', models.CharField(max_length=10, null=True)),
                ('code_en', models.CharField(max_length=10, null=True)),
                ('code_original', models.CharField(max_length=10, null=True)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30, null=True)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('name_original', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code_tm', models.CharField(max_length=10)),
                ('code_ru', models.CharField(max_length=10)),
                ('code_en', models.CharField(max_length=10)),
                ('code_original', models.CharField(max_length=10)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('name_original', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('long_name_tm', models.CharField(max_length=255)),
                ('long_name_ru', models.CharField(max_length=255)),
                ('long_name_en', models.CharField(max_length=255)),
                ('long_name_original', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('long_name_tm', models.CharField(max_length=255)),
                ('long_name_ru', models.CharField(max_length=255)),
                ('long_name_en', models.CharField(max_length=255)),
                ('long_name_original', models.CharField(max_length=255)),
                ('contract_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_original', models.CharField(max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('is_material', models.BooleanField(default=True)),
                ('is_mincons', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.basecompanycountry')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.basecompanyunit')),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30, null=True)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('name_original', models.CharField(max_length=30, null=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='company.basecompanytrade')),
            ],
        ),
        migrations.CreateModel(
            name='BaseCompanyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='company.basecompanyboqitem')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_consumptions', to='company.basecompanyresource')),
            ],
        ),
        migrations.AddField(
            model_name='basecompanyboqitem',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boq_items', to='company.basecompanylot'),
        ),
        migrations.AddField(
            model_name='basecompanyboqitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.basecompanyunit'),
        ),
    ]
