# Generated by Django 4.2.8 on 2023-12-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecompanyboqitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='company_boq_items', to='company.company'),
            preserve_default=False,
        ),
    ]
