# Generated by Django 4.2.6 on 2023-10-31 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_version', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('contract_number', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.project')),
            ],
        ),
        migrations.CreateModel(
            name='BoqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('labot_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smeta.boq')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.lot')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.trade')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.unit')),
            ],
        ),
    ]
