# Generated by Django 4.2.7 on 2023-11-29 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_country'),
        ('smeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RenameField(
            model_name='boqitem',
            old_name='labot_unit_price',
            new_name='labor_unit_price',
        ),
        migrations.CreateModel(
            name='MaterialCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.country')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeta.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='boq_item',
            field=models.ManyToManyField(related_name='materials', to='smeta.boqitem'),
        ),
        migrations.AddField(
            model_name='material',
            name='countries',
            field=models.ManyToManyField(through='smeta.MaterialCountry', to='common.country'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.unit'),
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.unit')),
            ],
        ),
    ]
