# Generated by Django 4.2.8 on 2023-12-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='boq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='smeta.boq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='boq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='smeta.boq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='boq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='smeta.boq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='boq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='smeta.boq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='boq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='smeta.boq'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_lots', to='smeta.trade'),
        ),
    ]
