# Generated by Django 4.2.8 on 2023-12-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0002_country_boq_currency_boq_lot_boq_trade_boq_unit_boq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='boq',
        ),
    ]
