# Generated by Django 4.2.8 on 2023-12-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0003_remove_lot_boq'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='boq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='smeta.boq'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='smeta.trade'),
        ),
    ]
