# Generated by Django 4.2.8 on 2023-12-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0004_resource_boq_alter_lot_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='smeta.trade'),
        ),
    ]
