# Generated by Django 4.2.8 on 2023-12-06 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_callingcode_country_calling_code_and_more'),
        ('smeta', '0006_remove_consumption_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boq_items', to='common.lot'),
        ),
    ]
