# Generated by Django 4.2.8 on 2023-12-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0007_alter_boqitem_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boqitem',
            name='trade',
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='name_original',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='transport_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
