# Generated by Django 4.2.8 on 2023-12-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0008_remove_boqitem_trade_alter_boqitem_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='is_material',
            field=models.BooleanField(default=True),
        ),
    ]
