# Generated by Django 4.2.8 on 2023-12-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_lot_code_alter_lot_index_alter_lot_name_en_and_more'),
        ('smeta', '0009_consumption_is_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='is_material',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='material',
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_material', models.BooleanField(default=True)),
                ('countries', models.ManyToManyField(through='smeta.MaterialCountry', to='common.country')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.unit')),
            ],
        ),
        migrations.AddField(
            model_name='consumption',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smeta.resource'),
        ),
        migrations.AlterField(
            model_name='materialcountry',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeta.resource'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
