# Generated by Django 4.2.8 on 2023-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0010_remove_consumption_is_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_original',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
