# Generated by Django 4.2.8 on 2023-12-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0013_resource_quantity_resource_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='resource',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1222, max_digits=12),
            preserve_default=False,
        ),
    ]
