# Generated by Django 4.2.8 on 2023-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0015_remove_resource_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_import',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_mincons',
            field=models.BooleanField(default=False),
        ),
    ]
