# Generated by Django 4.2.8 on 2023-12-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_lot_code_alter_lot_index_alter_lot_name_en_and_more'),
        ('smeta', '0016_resource_is_import_resource_is_mincons'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.country')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeta.resource')),
            ],
        ),
    ]
