# Generated by Django 4.2.8 on 2023-12-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_lot_code_alter_lot_index_alter_lot_name_en_and_more'),
        ('smeta', '0017_materialinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='countries',
            field=models.ManyToManyField(through='smeta.MaterialInfo', to='common.country'),
        ),
    ]
