# Generated by Django 4.2.8 on 2023-12-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_lot_code_alter_lot_index_alter_lot_name_en_and_more'),
        ('smeta', '0018_alter_resource_countries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialInfo',
            new_name='MaterialExtraInfo',
        ),
    ]
