# Generated by Django 4.2.8 on 2023-12-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0019_rename_materialinfo_materialextrainfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialCountry',
        ),
    ]
