# Generated by Django 4.2.8 on 2023-12-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0021_rename_countries_resource_extrainfos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='extrainfos',
            new_name='extra_infos',
        ),
    ]
