# Generated by Django 4.2.8 on 2023-12-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0022_rename_extrainfos_resource_extra_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=111, max_digits=12),
            preserve_default=False,
        ),
    ]
