# Generated by Django 4.2.8 on 2023-12-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0023_consumption_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
