# Generated by Django 4.2.8 on 2023-12-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0024_alter_consumption_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
