# Generated by Django 4.2.8 on 2023-12-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0025_alter_resource_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialextrainfo',
            old_name='model',
            new_name='brand',
        ),
    ]
