# Generated by Django 4.2.8 on 2023-12-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0026_rename_model_materialextrainfo_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='extra_infos',
        ),
        migrations.AlterField(
            model_name='materialextrainfo',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_infos', to='smeta.resource'),
        ),
    ]
