# Generated by Django 4.2.8 on 2023-12-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_lot_code_alter_lot_index_alter_lot_name_en_and_more'),
        ('smeta', '0028_remove_resource_is_import_materialextrainfo_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.country'),
        ),
    ]
