# Generated by Django 4.2.7 on 2023-11-29 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0002_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='boq_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='smeta.boqitem'),
            preserve_default=False,
        ),
    ]
