# Generated by Django 4.2.7 on 2023-11-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0004_rename_boq_item_material_boq_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='boq_items',
        ),
        migrations.AddField(
            model_name='consumption',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smeta.material'),
            preserve_default=False,
        ),
    ]
