# Generated by Django 4.2.7 on 2023-11-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0005_remove_material_boq_items_consumption_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='name_original',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='name_tm',
        ),
    ]
