# Generated by Django 4.2.6 on 2023-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('long_name_tm', models.CharField(max_length=255)),
                ('long_name_ru', models.CharField(max_length=255)),
                ('long_name_en', models.CharField(max_length=255)),
                ('long_name_original', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_original', models.CharField(max_length=255)),
                ('long_name_tm', models.CharField(max_length=255)),
                ('long_name_ru', models.CharField(max_length=255)),
                ('long_name_en', models.CharField(max_length=255)),
                ('long_name_original', models.CharField(max_length=255)),
                ('contract_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
