# Generated by Django 4.2.6 on 2023-10-31 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('short_name_tm', models.CharField(max_length=20)),
                ('short_name_ru', models.CharField(max_length=20)),
                ('short_name_en', models.CharField(max_length=20)),
                ('short_name_original', models.CharField(max_length=20)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('name_original', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code_tm', models.CharField(max_length=10)),
                ('code_ru', models.CharField(max_length=10)),
                ('code_en', models.CharField(max_length=10)),
                ('code_original', models.CharField(max_length=10)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('name_original', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code_tm', models.CharField(max_length=10)),
                ('code_ru', models.CharField(max_length=10)),
                ('code_en', models.CharField(max_length=10)),
                ('code_original', models.CharField(max_length=10)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('name_original', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('name_tm', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('name_original', models.CharField(max_length=30)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.trade')),
            ],
        ),
    ]
