# Generated by Django 4.2.8 on 2023-12-06 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='callingCode',
            new_name='calling_code',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='code3Letter',
            new_name='code_3_letter',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='numericCode',
            new_name='numeric_code',
        ),
        migrations.AlterField(
            model_name='lot',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='common.trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='code_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='code_original',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='code_ru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='code_tm',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='name_original',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
