# Generated by Django 4.2.8 on 2023-12-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_callingcode_country_calling_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name_original',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
